import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from "@/app/components/shared/Navbar/Navbar";
import Header from "@/app/components/shared/Header/Header";
import '../../globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="containerClient">

                      <Navbar
              conTentNavigation = {
                {
                  logo:'/images/logoWebsite.png',
                  navItems:[
                    {icon:`bi bi-file-earmark-text-fill`,text:"Tiếp nhận", link:'https://media-cdn-v2.laodong.vn/storage/newsportal/2024/7/16/1367312/Benh-Vien-Tam-Anh-3.jpeg'},
                    {icon:`bi bi-search`,text:"Tra cứu thẻ khám", link:'https://media-cdn-v2.laodong.vn/storage/newsportal/2024/7/16/1367312/Benh-Vien-Tam-Anh-3.jpeg'}
                  ]
                }
              }
            >
          </Navbar>

              <div className="containerClient__content">
            <Header>
                  
            </Header>


        {children}
              </div>


        </div>

      </body>
    </html>
  );
}
